# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from default_pkg/lift_goal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class lift_goal(genpy.Message):
  _md5sum = "14995ce8af4d2f12e7ff9eb6001809c7"
  _type = "default_pkg/lift_goal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# lift_goal.msg
# defines the movement goal tof the 8 lifts
# 1 = top ; -1 = bottom ; 0 = STOP;
int8 lift_goal0
int8 lift_goal1
int8 lift_goal2
int8 lift_goal3
int8 lift_goal4
int8 lift_goal5
int8 lift_goal6
int8 lift_goal7"""
  __slots__ = ['lift_goal0','lift_goal1','lift_goal2','lift_goal3','lift_goal4','lift_goal5','lift_goal6','lift_goal7']
  _slot_types = ['int8','int8','int8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lift_goal0,lift_goal1,lift_goal2,lift_goal3,lift_goal4,lift_goal5,lift_goal6,lift_goal7

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(lift_goal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lift_goal0 is None:
        self.lift_goal0 = 0
      if self.lift_goal1 is None:
        self.lift_goal1 = 0
      if self.lift_goal2 is None:
        self.lift_goal2 = 0
      if self.lift_goal3 is None:
        self.lift_goal3 = 0
      if self.lift_goal4 is None:
        self.lift_goal4 = 0
      if self.lift_goal5 is None:
        self.lift_goal5 = 0
      if self.lift_goal6 is None:
        self.lift_goal6 = 0
      if self.lift_goal7 is None:
        self.lift_goal7 = 0
    else:
      self.lift_goal0 = 0
      self.lift_goal1 = 0
      self.lift_goal2 = 0
      self.lift_goal3 = 0
      self.lift_goal4 = 0
      self.lift_goal5 = 0
      self.lift_goal6 = 0
      self.lift_goal7 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8b().pack(_x.lift_goal0, _x.lift_goal1, _x.lift_goal2, _x.lift_goal3, _x.lift_goal4, _x.lift_goal5, _x.lift_goal6, _x.lift_goal7))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.lift_goal0, _x.lift_goal1, _x.lift_goal2, _x.lift_goal3, _x.lift_goal4, _x.lift_goal5, _x.lift_goal6, _x.lift_goal7,) = _get_struct_8b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8b().pack(_x.lift_goal0, _x.lift_goal1, _x.lift_goal2, _x.lift_goal3, _x.lift_goal4, _x.lift_goal5, _x.lift_goal6, _x.lift_goal7))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.lift_goal0, _x.lift_goal1, _x.lift_goal2, _x.lift_goal3, _x.lift_goal4, _x.lift_goal5, _x.lift_goal6, _x.lift_goal7,) = _get_struct_8b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8b = None
def _get_struct_8b():
    global _struct_8b
    if _struct_8b is None:
        _struct_8b = struct.Struct("<8b")
    return _struct_8b
