(cl:in-package default_pkg-msg)
(cl:export '(USB_IDENT0-VAL
          USB_IDENT0
          USB_LOC0-VAL
          USB_LOC0
          USB_IDENT1-VAL
          USB_IDENT1
          USB_LOC1-VAL
          USB_LOC1
          USB_IDENT2-VAL
          USB_IDENT2
          USB_LOC2-VAL
          USB_LOC2
          USB_IDENT3-VAL
          USB_IDENT3
          USB_LOC3-VAL
          USB_LOC3
          USB_IDENT4-VAL
          USB_IDENT4
          USB_LOC4-VAL
          USB_LOC4
          USB_IDENT5-VAL
          USB_IDENT5
          USB_LOC5-VAL
          USB_LOC5
          USB_IDENT6-VAL
          USB_IDENT6
          USB_LOC6-VAL
          USB_LOC6
          USB_IDENT7-VAL
          USB_IDENT7
          USB_LOC7-VAL
          USB_LOC7
          USB_IDENT8-VAL
          USB_IDENT8
          USB_LOC8-VAL
          USB_LOC8
          USB_IDENT9-VAL
          USB_IDENT9
          USB_LOC9-VAL
          USB_LOC9
))