(cl:in-package default_pkg-msg)
(cl:export '(RANGE_SI0-VAL
          RANGE_SI0
          RANGE_SI1-VAL
          RANGE_SI1
          RANGE_SI2-VAL
          RANGE_SI2
          RANGE_SI3-VAL
          RANGE_SI3
          RANGE_SI4-VAL
          RANGE_SI4
          RANGE_SI5-VAL
          RANGE_SI5
          RANGE_SI6-VAL
          RANGE_SI6
          RANGE_SI7-VAL
          RANGE_SI7
          RANGE_SI8-VAL
          RANGE_SI8
          RANGE_SI9-VAL
          RANGE_SI9
          RANGE_SI10-VAL
          RANGE_SI10
          RANGE_SI11-VAL
          RANGE_SI11
          RANGE_SI12-VAL
          RANGE_SI12
          RANGE_SI13-VAL
          RANGE_SI13
          RANGE_SI14-VAL
          RANGE_SI14
          RANGE_SI15-VAL
          RANGE_SI15
))