// Generated by gencpp from file default_pkg/test.msg
// DO NOT EDIT!


#ifndef DEFAULT_PKG_MESSAGE_TEST_H
#define DEFAULT_PKG_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace default_pkg
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : pos1(0)
    , pos2(0)  {
    }
  test_(const ContainerAllocator& _alloc)
    : pos1(0)
    , pos2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _pos1_type;
  _pos1_type pos1;

   typedef uint8_t _pos2_type;
  _pos2_type pos2;




  typedef boost::shared_ptr< ::default_pkg::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::default_pkg::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::default_pkg::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::default_pkg::test > testPtr;
typedef boost::shared_ptr< ::default_pkg::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::default_pkg::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::default_pkg::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace default_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'default_pkg': ['/home/labh/plattform-ros/src/default_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::default_pkg::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::default_pkg::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::default_pkg::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::default_pkg::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::default_pkg::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::default_pkg::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::default_pkg::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fbb8772d895b809b44d055737e339ee";
  }

  static const char* value(const ::default_pkg::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fbb8772d895b809ULL;
  static const uint64_t static_value2 = 0xb44d055737e339eeULL;
};

template<class ContainerAllocator>
struct DataType< ::default_pkg::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "default_pkg/test";
  }

  static const char* value(const ::default_pkg::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::default_pkg::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# this is a Message for Testing purpose\n\
uint8 pos1\n\
uint8 pos2\n\
";
  }

  static const char* value(const ::default_pkg::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::default_pkg::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos1);
      stream.next(m.pos2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::default_pkg::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::default_pkg::test_<ContainerAllocator>& v)
  {
    s << indent << "pos1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos1);
    s << indent << "pos2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEFAULT_PKG_MESSAGE_TEST_H
